### ISSUE TITLE
doesn't work without staticsite

### ISSUE THREAD

**Issue by anarcat** [spanezz/mdpreview#1]
hi!

i was curious to try this with my ikiwiki blog. yet it seems i also need to install staticsite for the binary to work at all:

```
$ ./mdpreview ~/wikis/anarc.at/blog/2016-03-31-free-software-activities-march-2016.mdwn
Traceback (most recent call last):
  File "./mdpreview", line 97, in <module>
    main()
  File "./mdpreview", line 92, in main
    preview = Mdpreview(args)
  File "./mdpreview", line 19, in __init__
    from staticsite.core import settings
ImportError: No module named 'staticsite'
```

is there a way to workaround that?

thanks!

**Comment by spanezz** [comment]
Hi. There isn't really a way to work around that: mdpreview is just a 97 lines script, that works as a different command line frontend to the functions in staticsite. In fact, it is pretty much equivalent to doing `ssite serve --theme /usr/share/doc/staticsite/example/theme --content . .`

I have been considering packaging the mdpreview executable as part of staticsite, and stopped because I felt that it would not be intuitive to connect the name `staticsite` to something that previews markdown documentation in a software project.

In fact, staticsite's library contains generic code for reading content in markdown and potentially other formats, interlinking them, and rendering them. That the name implies it can preview and build static sites reflects more what I built it for than what it can do.

I could use ideas for improving this situation. Can you think of ways of making it better?

**Comment by anarcat** [comment]
On 2016-04-01 05:45:55, Enrico Zini wrote:

> Hi. There isn't really a way to work around that: mdpreview is just a 97 lines script, that works as a different command line frontend to the functions in staticsite. In fact, it is pretty much equivalent to doing `ssite serve --theme /usr/share/doc/staticsite/example/theme --content . .`
> 
> I have been considering packaging the mdpreview executable as part of staticsite, and stopped because I felt that it would not be intuitive to connect the name `staticsite` to something that previews markdown documentation in a software project.
> 
> In fact, staticsite's library contains generic code for reading content in markdown and potentially other formats, interlinking them, and rendering them. That the name implies it can preview and build static sites reflects more what I built it for than what it can do.
> 
> I could use ideas for improving this situation. Can you think of ways of making it better?

I guess that if all of this would be in Debian stable, I could have just
installed staticsite already and we wouldn't be having this
conversation. :)

## a.

There has been only one Christian.
They caught him and crucified him -- early.
                        - Mark Twain

**Comment by spanezz** [comment]
So far I only opened an RFP of the only missing dependency of staticsite in Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816727
...after which, packaging staticsite should be easy.

I have given up being both upstream and Debian packager, and decided that if there is enough interest for a software of mine to be in Debian, then there can be another person/user taking care of the packaging.

I'd like it if that happened. Would you like to have a go at it?

**Comment by anarcat** [comment]
On 2016-04-01 09:26:29, Enrico Zini wrote:

> I'd like it if that happened. Would you like to have a stab at it?

Unfortunately, I'm still in ikiwiki-land so it's unlikely that i will
use this in the short term.

I encourage you to package it anyways, there's nothing wrong with
packaging your own software in Debian, even though it is a little taboo.

a.

**Comment by spanezz** [comment]
It's not really because of a taboo, it's because I've done it for years and decided I really do not enjoy doing that.

**Comment by anarcat** [comment]
i see. it's alright, and i think i can just close this for now, i understand the reasoning better.
